### ISSUE TITLE
Large files in cargo package source

### ISSUE THREAD

**Issue by bluss** [maidsafe/sodiumoxide#16]
maidsafe_sodiumoxide 0.0.12 has a 6 MB ./bin/x86_64-pc-windows-gnu/ directory in its cargo package source. Consider releasing a new clean version.

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by Fraser999** [comment]
Thanks for the report.  Fixed in https://github.com/maidsafe/sodiumoxide/commit/b619e0f7db5b13b0d0912fa67c238de6d1b3862e.
